const fs = require('fs');

const extendedDescriptions = {
    1: "Contributed as a core mechanical team member for an advanced competition-level autonomous rover designed for the Caterpillar Autonomy Challenge. The goal of this project was to achieve true autonomous navigation and object manipulation on uneven terrain. To overcome significant integration challenges, I utilized structural welding to build a high-durability chassis capable of withstanding heavy loads and collisions. A major innovation was developing the articulated bucket mechanism from scratch, allowing for precise autonomous digging and dumping. In addition to the mechanics, I led the cross-team electronics coordination, ensuring our sensor suits (LiDAR, IMU, and stereo cameras) were safely mounted and accurately calibrated for the SLAM algorithms. This project marked a significant transition from hobbyist prototyping into industry-standard mechatronics team workflows, requiring rigorous testing, version control, and mechanical simulation.",
    
    2: "This project was developed collaboratively with peers at PSG College of Technology as an experimental side project to bridge the gap between theoretical control systems and practical mechatronics. The robot utilizes a low-latency infrared (IR) sensor array to detect contrast differences on the floor track, feeding data into a high-speed microcontroller. By implementing a custom proportional-integral-derivative (PID) control algorithm, the system continuously adjusts the pulse-width modulation (PWM) signals sent to the dual-drive DC motors. This allowed the robot to achieve stable, jitter-free path tracking across sharp curves, intersections, and varying light conditions. The build process served as a fantastic deep-dive into low-level logic, encoder feedback loops, and rapid electronics prototyping.",
    
    3: "Built as a highly dependable tool for rapid prototyping, this machine was designed from the ground up to overcome the thermal and friction limits experienced in my V1 build. To achieve maximum print speed without sacrificing surface quality, I migrated the entire motion planning stack to a host laptop running Klipper firmware. This drastically increased the step rates and enabled advanced features like input shaping (resonance compensation) and pressure advance. The physical mechanics include a rigid aluminum extrusion frame, upgraded NEMA 17 steppers with aggressive cooling, and high-tolerance linear rails. The resulting machine delivers highly consistent extrusion and reliable dimensional accuracy, significantly decreasing my iteration time for subsequent mechanical design projects.",
    
    4: "This DIY 3D printer was my very first hands-on architecture build, utilizing incredibly unorthodox materials to achieve CNC motion. Instead of traditional linear rails, I engineered the X and Y axes using heavy-duty telescopic drawer slides mounted onto a manually welded mild-steel frame. This gave the printer immense rigidity, albeit with complex inertia challenges. The absolute highlight of this build was the electronics: rather than buying an off-the-shelf motherboard, I designed and etched a completely custom multi-heater control PCB. This board handled high-current multiplexing for the heated bed, the hotend thermistors, and an experimental plastic recycling extrudate system.",
    
    5: "Developed rigorously over 8 full design iterations, this 6-degree-of-freedom robotic arm stands as one of my most innovative mechanical challenges. Attempting to keep the budget near-zero, the arm is driven entirely by scavenged and scrap stepper motors. Because off-the-shelf precision bearings were too expensive, I developed a unique sand-tuned PVC pseudo-bearing system and hand-cut mica transmission gears to handle the immense torque required at the shoulder and elbow joints. The electronic brain is a 6-axis GRBL controller parsing G-Code streams to interpolate complex splines and inverse-kinematics. Against all odds, this scrap-built arm achieved competition-winning precision capable of repeatable pick-and-place tasks.",
    
    6: "Before tackling complex stepper control, I built this 6-axis arm to understand the absolute limits of raw DC motor power. The entire structure was powered by salvaged, extremely high-torque actuators, including a heavy lorry windshield wiper motor and assorted automotive gearboxes. The entire system ran on an open-loop bang-bang control architecture, manually switched via custom-soldered high-current relay arrays. Despite having no precise rotary encoders, the raw holding torque and mechanical gearing allowed the arm to hand-position up to 500 grams of payload at full extension. This rudimentary but incredibly powerful system surprisingly outperformed a ₹6-lakh educational robot in sheer lifting capacity and mechanical durability.",
    
    7: "A brilliant exercise in micro-fabrication and salvaged technology, this ultra-precise plotter was constructed using the integrated lead screw and guide rail assemblies scavenged from old discarded DVD drives. By repurposing the laser-head stepper motors and combining them on a miniature 3D-printed chassis, I created an X-Y stage with sub-millimeter repeatable accuracy. Driven by an Arduino running GRBL firmware, it translates vector G-code into incredibly fine ink drawings on a tiny 5x5 cm grid. This project perfectly demonstrated that high-tolerance linear guides, even those found in e-waste, can achieve spectacular CNC precision when paired with good software.",
    
    8: "Moving away from standard Cartesian (X, Y, Z) mechanics, this project explored a non-Cartesian cable-driven wall plotter. The end effector (a pen holder) hangs vertically and is positioned entirely by gravity and the tension of two strings winding around stepper motor spools mounted at the top corners of a whiteboard. The software challenge was immense: it required writing and configuring an algorithm that constantly transforms Cartesian coordinate inputs into polar string-length equations in real-time. This project pushed my understanding of advanced computational kinematics, managing mechanical resonance in cables, and translating mathematical motion curves into physical art.",
    
    9: "Learning from the severe cantilever deflection issues of my V1 plotter, the Improved V2 was completely redesigned using a bridge-style gantry layout to separate the X and Y axes independently. Built using V-slot aluminum extrusions, proper polyurethane GT2 timing belts, and a customized Arduino CNC shield, the mechanical rigidity was massively increased. This stiffness practically eliminated pen wobble at high speeds. Leveraging optimized GRBL acceleration parameters, the platform achieved massive improvements in plotting accuracy, capable of consistently tracing over the exact same vector paths multiple times without any visible deviation.",
    
    10: "This was my very first attempt at building an automated computer numerical control (CNC) mechanism. Constrained by a lack of budget and standard parts, I constructed an overhanging motion rig out of solid wooden blocks, utilizing threaded trapezoidal rods for drive transmission. For linear bearings, I innovatively adapted lubricated syringe caps that slid over smooth metal rails. Dealing with heavy constraints regarding belt tensioning and wooden friction taught me the hard realities of mechanical tolerance. While slow and slightly imprecise, it successfully parsed its first G-code and established the core foundation for all my future precision robotic builds.",
    
    11: "Engineered directly as a solution for a grueling agricultural challenge, this tool was built to dig 4-inch diameter holes down to 1.5 feet deep for fencing and post implementation. Traditional manual augers require immense physical exhaustion when dealing with compacted, aggregate-rich bedrock soils. I solved this by salvaging a high-torque electric e-bike hub motor, heavily gearing it down, and mounting it to a custom-welded structural steel handle assembly. The resulting motorized auger slices through dense soil and roots with ease, completely eliminating the extreme manual labor previously required on the farm.",
    
    12: "Developed to meet the exhausting, high-volume liquid application requirements for organic crop protection on large agricultural plots. Carrying 15-liter backpack sprayers all day causes severe back fatigue and inefficiency. To fix this, I engineered a highly stable, large-wheel rolling trolley that integrates a massive 150-liter liquid tank. Plumbed securely to the tank is a 12V high-pressure electric diaphragm pump powered by a deep-cycle battery. Connected to over 100 meters of high-pressure braided hose, the operator can simply park the trolley centrally and walk the crop rows freely, drastically increasing farm efficiency and worker ergonomics.",
    
    13: "This machine is a direct ergonomic upgrade to the handheld rotary finger weeder. The handheld version required the operator to constantly support the weight of the motor over the crops. By implementing a ground-supported, single-wheel agricultural chassis, I completely transferred the structural load to the earth. The spinning flexible tines agitate the soil to uproot juvenile weeds without using toxic herbicides. The addition of the wheel stabilized the soil disruption depth to a perfect 2 cm, vastly enlarged the daily operating coverage, and entirely solved the physical spinal strain issues faced by operators.",
    
    14: "An experimental, portable 12V electric weed eradicator designed for highly localized precision agriculture. Using rotating flexible rubber tines mounted to a high-speed DC motor, the tool violently agitates the top 1 to 2 centimeters of the topsoil. This specific depth is calculated to pull up and expose the delicate root networks of ~10-day-old weeds, leaving them on the surface for rapid solar desiccation while avoiding any damage to the deeper root systems of the actual crops. It represents my first attempt at non-chemical, mechanized weed control systems.",
    
    15: "This project electrified a traditional, grueling manual push weeder by incorporating a massive 350W high-torque BLDC e-bike motor. The immediate engineering hurdle was transferring that electrical torque into raw ground traction without the wheel simply slipping in the mud. I overcame these major soil traction limitations by designing a focused chain-and-sprocket reduction transmission and welding aggressive metal cleats directly onto the main drive wheel. The resulting tiller practically pulls itself through the soil, vastly reducing operator fatigue and doubling the speed of mechanical weeding.",
    
    16: "Built as an exercise in traditional agricultural implement fabrication, this tool comprises a lightweight, highly optimized structural steel frame focusing on maneuverability and direct kinetic energy application. By transferring the linear pushing force of the human body through a large fulcrum wheel, it effortlessly slices a sharpened V-blade beneath the topsoil to sever weed stems. This extremely simple but reliable design substantially decreased the physical and cardiovascular demands imposed by traditional hand-held hoeing techniques, proving that simple geometric leverage is sometimes the best solution.",
    
    17: "Traditional brush cutters and line trimmers require the operator to wear a heavy, vibrating 2-stroke engine on their back, leading to spinal compression and fatigue during prolonged field clearing. To eliminate this, I migrated the trimmer cutting hardware onto a heavy-duty rolling cart frame. To power the cutters without a gas engine, I resourcefully repurposed and overvolted 12V automotive radiator cooling fans, which provided surprisingly violent RPMs and high torque. The result was a quiet, emissions-free, push-cart brush cutter that adequately leveled heavy crop clearance and tall grasses with zero operator strain.",
    
    18: "Traditional paper cup forming machines represent an immense capital investment, often utilizing massive 10-foot long industrial setups. For my first foray into manufacturing logistics, I designed a condensed, highly compact alternative concept aimed at small-scale viability. I successfully engineered a miniature PVC-driven conveyor track and analyzed the complex mechanical forming geometries required to curl and seal paper tubes. Though purely a proof-of-concept prototype, building it gave me incredibly early insights into automated logistics, cam-driven actuation, and assembly line chain optimization.",
    
    19: "This was a sturdy, aggressive combat robot assembled specifically for internal college-level skirmishes and arena combat. Unlike standard rovers that prioritize sensor feedback and pathing, this machine's design focus was shifted entirely toward extreme reliability, impact resistance, and raw kinetic delivery. Utilizing high-amperage H-bridges, twin high-power DC drive trains, and a heavily armored wedge chassis, it was built to take severe physical punishment. Designing this taught me crucial lessons about electrical fault tolerance, battery shock-mounting, and structural stress dissipation.",
    
    20: "This stands as my very first, foundational mechatronics project. Built entirely from electronic waste, it is a manually operated ground surveyor. I cascaded basic BC547 NPN transistors to build crude amplification circuits that successfully detected temperature, moisture, and fire anomalies via analog probes. Having no budget for standard gear motors, I violently modified and scavenged the 12V DC motors hidden inside old Reverse Osmosis (RO) filtration water pumps to act as the drive train. Despite its extremely humble origins, it was fully functional and was proudly presented at an early National Level technical event."
};

let mainJs = fs.readFileSync('main.js', 'utf8');

for (const [id, newDesc] of Object.entries(extendedDescriptions)) {
    // Regex matches the start of the object up to fullDesc: "..."
    const regex = new RegExp(`(id:\\s*${id},\\s*[\\s\\S]*?fullDesc:\\s*")[\\s\\S]*?("\\,\\s*tags:)`);
    const escapedDesc = newDesc.replace(/"/g, '\\"');
    mainJs = mainJs.replace(regex, `$1${escapedDesc}$2`);
}

fs.writeFileSync('main.js', mainJs);
console.log("Descriptions updated successfully!");
